name: Build & Deploy

on:
  push:
    branches:
    - main
    paths:
    - 'S0142/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'SmokeFunc001'        # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './S0142'     # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                       # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  # 1. BUILD
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./S0142

    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        # dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: display cwd
        run: pwd
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  # 2. DEPLOY
  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    # scm-do-build-during-deployment: 'true' (explicit command for creating function apps via github workflow)
    # enable-oryx-build: 'true' (for linux but i'm trying it anyway)
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: 'true'
        enable-oryx-build: 'true'
